### ISSUE TITLE
Add section for startups?

### ISSUE THREAD

**Issue by tif-calin** [jah2488/elm-companies#109]
What would you think of adding a new section specifically for small startups? I've come across a few that have Elm in their stack but I'm not sure if people would want the whole list populated with them. Here some examples:

https://www.workatastartup.com/companies/flint
https://www.workatastartup.com/companies/deepgram
https://www.workatastartup.com/companies/heroic-labs

**Comment by jah2488** [comment]
Small Startups are certainly allowed, but they should be submitted within the section for what their startup is doing.
