### ISSUE TITLE
Would Microsoft's elm-json-tree-view package count as them using Elm in production?

### ISSUE THREAD

**Issue by r-k-b** [jah2488/elm-companies#36]
Microsoft have published an Elm module: <https://github.com/Microsoft/elm-json-tree-view>, <http://package.elm-lang.org/packages/Microsoft/elm-json-tree-view/latest>.

Would that be enough to count Microsoft as "using it in production?"

If so, which section should it appear under?

**Comment by nelsonic** [comment]
@klazuka creator of https://github.com/klazuka/intellij-elm and https://github.com/klazuka/elm-json-tree-view works for MSFT. They might be able to offer some insight into MSFT's use of Elm in Production. 💡

**Comment by klazuka** [comment]
I have been using Elm in production at Microsoft since 2016. It is the frontend for a customer support system.
