### ISSUE TITLE
Add Webbhuset to list in Consulting Section

### ISSUE THREAD

**Issue by nelsonic** [jah2488/elm-companies#50]
**Webbhuset** https://webbhuset.se https://github.com/webbhuset based in Gothenburg Sweden builds E-Commerce websites for several major brands including L'ORÉAL, Mary Kay and HaperCollins. According to this Elm Europe talk by @albertdahlin they have shipped 6 Elm SPAs to production:
[![image](https://user-images.githubusercontent.com/194400/70514571-d50a7f00-1b2b-11ea-8886-63922445901e.png)](https://youtu.be/YV_qrjN8bRA?t=68)
https://youtu.be/YV_qrjN8bRA?t=68

**Comment by jah2488** [comment]
I'd say adding them makes sense given we have this talk as a direct source 👍

**Comment by nelsonic** [comment]
@jah2488 thanks for confirming. Please see PR: https://github.com/jah2488/elm-companies/pull/52 👍
