### ISSUE TITLE
Add Brilliant.org learning platform to Education section

### ISSUE THREAD

**Issue by nelsonic** [jah2488/elm-companies#51]
While searching for more companies using Elm on Stack Share https://www.stackshare.io/elm
I noticed that Brilliant https://brilliant.org is using Elm: https://www.stackshare.io/brilliant/brilliant
![brilliant-using-elm-in-production](https://user-images.githubusercontent.com/194400/70534442-fb8fe080-1b52-11ea-8f5d-0b5f4c8c2ddb.png)

I think it's worth adding to the Education section https://github.com/jah2488/elm-companies#education
because they are a recognisable brand and they have a _really_ good learning platform.
They aren't super into Open Source, so their GitHub https://github.com/brilliantorg doesn't have any Elm.
Stackshare.io requires verification for people adding tech to a company profile,
so we can reasonably trust that they are actually using it in production.

Happy to create the PR if you agree. 👍

**Comment by lucamug** [comment]
Actually they have two projects on GitHub: https://github.com/orgs/brilliantorg/repositories?language=elm

**Comment by nelsonic** [comment]
@lucamug perfect. Can I PR the addition? 👨‍💻

**Comment by nelsonic** [comment]
PR: https://github.com/jah2488/elm-companies/pull/105
