### ISSUE TITLE
Add Amazon, Ebay, Ford etc. featured in Richard Feldman's talk?

### ISSUE THREAD

**Issue by Herteby** [jah2488/elm-companies#62]
@rtfeldman made this slide with notable companies using Elm for one of his talks. Several of them are not on this list. I wonder what their exact status regarding Elm is, are they indeed all using it "in production", and if it happens to only be for some small internal tool, should it count? :slightly_smiling_face: 

https://youtu.be/sKxEwjKQ5zg?t=305
![image](https://user-images.githubusercontent.com/6474685/72812900-a7544200-3c62-11ea-89a4-c7d3d0e4f625.png)

**Comment by jah2488** [comment]
Personally, I feel the links in this list should be added by people directly associated with the company being added.

Perhaps it would make sense to add a different section for these larger companies that we _believe_ are using it, but can't verify directly.
