### ISSUE TITLE
Add Southern Exposure Seed Exchange

### ISSUE THREAD

**Issue by prikhi** [jah2488/elm-companies#73]
[SESE](https://github.com/Southern-Exposure-Seed-Exchange) uses Elm for our [eCommerce website](https://github.com/Southern-Exposure-Seed-Exchange/southernexposure.com):

https://www.southernexposure.com/

**Comment by Herteby** [comment]
You should create a PR for it. Just click edit on the [README.md](https://github.com/jah2488/elm-companies/blob/master/README.md) on GitHub and follow the steps.
